# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: The Expert Group (DLI)
email: adarshbm11@gmail.com
description: "With a blend of creativity, innovation, strategy, and craft, we help you solve business problems."


# Team names, titles and social links
people:
- name: Nithin Bhasker 
  pic: 1
  position: System Admin, Microsoft Certified Solutions Expert
  social:
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/nithin-bhasker-130460148
    - title: facebook
      url: https://www.facebook.com/nithinbhasker
      
      
- name: Akhil Pradeep
  pic: 2
  position: Graphic Designer
  social:
    - title: twitter
      url: https://twitter.com/akhilprkp11
    - title: facebook
      url: https://www.facebook.com/akhil.pradeep.92

      
- name: Adarsh B
  pic: 3
  position: Technical Communicator
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/adarshbalachandran
    - title: google-plus
      url: https://plus.google.com/+AdarshBalachandran
    - title: facebook
      url: https://www.facebook.com/adarsh.master
   - title: twitter
      url: https://twitter.com/adarshb82

      
- name: Shesna PA
  pic: 4
  position: Technical Communicator
  social:
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/shesna-p-a-2550249a
    - title: google-plus
      url: https://plus.google.com/109179778173955208466
    - title: facebook
      url: https://www.facebook.com/shezna.pa
   - title: twitter 
      url: https://twitter.com/Shezna_pa?s=09

# Postal address (add as many lines as necessary)
address:
  - line: Sarada Mandiram, Calicut
  - line: Spinning Mill, Chelembra, Malappuram

# Build settings
markdown: kramdown
permalink: pretty
