# url: https://y7kim.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: The Expert Group (DLI)
email: adarshbm11@gmail.com
description: "With a blend of creativity, innovation, strategy, and craft, we help you solve business problems."


# Team names, titles and social links
people:
- name: Nithin Bhasker 
  pic: 2
  position: System Admin, Microsoft Certified Solutions Expert
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Akhil Pradeep
  pic: 1
  position: Graphic Designer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #
      
- name: Adarsh B
  pic: 3
  position: Lead Documentation Engineer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
      
- name: Shesna PA
  pic: 4
  position: Sr. Tech Writer
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket 
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: Sarada Mandiram, Calicut
  - line: Spinning Mill, Chelembra, Malappuram

# Build settings
markdown: kramdown
permalink: pretty
